version: '3.8'
services:
  foo:
    networks:
    - shared
    environment:
    - MAGIC_HOST=http://bar:8080
    build:
      context: "./"
    ports:
      - "3000:8080"
  bar:
    networks:
    - shared
    build:
      context: "../service_b/"
    ports:
      - "3001:8080"
networks:
    shared:
